### ISSUE TITLE
bot wont level up 100 iv pokemon

### ISSUE THREAD

**Issue by WZX** [NECROBOTIO/NecroBot#3215]
"UpgradePokemonIvMinimum": 98.0, 

it will only level up some iv 98.x 99.x pokemon  but not iv 100

why ?

**Comment by Saiteik** [comment]
Looking into this method now, I will get back to you

**Comment by Saiteik** [comment]
Please send me the following area of your config:

//powerup
        [DefaultValue(false)]
        public bool AutomaticallyLevelUpPokemon;
        [DefaultValue(5)]
        public int AmountOfTimesToUpgradeLoop;
        [DefaultValue(5000)]
        public int GetMinStarDustForLevelUp;
        [DefaultValue("iv")]
        public string LevelUpByCPorIv;
        [DefaultValue(1000)]
        public float UpgradePokemonCpMinimum;
        [DefaultValue(95)]
        public float UpgradePokemonIvMinimum;
        [DefaultValue("and")]
        public string UpgradePokemonMinimumStatsOperator;

**Comment by WZX** [comment]
"AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 98.5,
  "UpgradePokemonMinimumStatsOperator": "and",



i set "UpgradePokemonIvMinimum": 100,  but found it doesn't work  ,
so i changed it to "UpgradePokemonIvMinimum": 98.5,  
and it will level up some 98.5+iv pokemon but not 100 iv

**Comment by Simpuhl** [comment]
This does that work for me either, 

I have it set to level up Pokémon that are 100.0 IV and it won't do it. This has been ongoing since beta version.

**Comment by Marsinator** [comment]
same.

  "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 800,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1500.0,
  "UpgradePokemonIvMinimum": 99.9,
  "UpgradePokemonMinimumStatsOperator": "and",

**Comment by Saiteik** [comment]
Can someone peer review my suggested change for this issue?

https://github.com/Saiteik/NecroBot/commit/b6154d56e714466243dca581a941dd3890273d74

**Comment by Saiteik** [comment]
#3320 This PR should fix this problem, I determined that the returned list was incorrect for upgrading by IV.

**Comment by Simpuhl** [comment]
Seems like this was fixed.

Not sure why its still open

**Comment by EvilEpicPanda** [comment]
It's actually still not working for me. 

>   "AutomaticallyLevelUpPokemon": true,
  "UseLevelUpList": false,
  "AmountOfTimesToUpgradeLoop": 10,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 500.0,
  "UpgradePokemonIvMinimum": 100.0,
  "UpgradePokemonMinimumStatsOperator": "and",

I have a few Dragonites with over 1000 CP and 100% IV, and it's not doing anything.

**Comment by nfettinger** [comment]
@EvilEpicPanda Please use Discord chat to solve your issue, we must assume it is a problem with your configuration first. If you can find the specific bug, then we can fix it.
