### ISSUE TITLE
BUG? Exception Error

### ISSUE THREAD

**Issue by jinkawasaki333** [NECROBOTIO/NecroBot#3618]
Here it is (ignore the Japanese text).

```
[15:01:32] System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   場所 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() 場所 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:行 195
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() 場所 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:行 67
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 場所 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:行 36
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---
```

**Comment by iPollox** [comment]
[02:07:42] System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

**Comment by jinkawasaki333** [comment]
@iPollox Thanks for the translation ;)

**Comment by iPollox** [comment]
@jinkawasaki333 I didn't translate it, I literally just got the same error, it's still working but it's a random bug that i've seen for the first time. Hopefully gets fixed.

**Comment by jinkawasaki333** [comment]
@iPollox Haha.. Yeah I know, it was a joke.
Well, 0.7.8 and 0.8.0 are buggy.. I'm using 7.7 which is the most stable I think.

**Comment by Gorgoroth0030** [comment]
When you decline the upgrade, does it make you redo your auth?

**Comment by nfettinger** [comment]
Fixed in 0.8.0

**Comment by jinkawasaki333** [comment]
@nfettinger Actually this problem comes after the 0.8.0 release. It's NOT FIXED.
