### ISSUE TITLE
incomplete Logs/Console info

### ISSUE THREAD

**Issue by Drunken88** [NECROBOTIO/NecroBot#4167]
I noticed that when using a mystery egg to evolve a lot of pokemon, the logs/console messages do not reflect the reality at all.

For example, I had 69 evolution to do, but the logs and console display only 19 evolutions. 
But in reality the bot did all the 69 evolutions then transferred them all.

Why all the evos are not displayed in the logs & the console? 
```
[23:21:13] [Evolution] Disponible : 69
[23:21:14] Utilisation d'un Œuf Chance, reste 1
[23:21:17] Roucool +1000XP
[23:21:45] Leveled up: 25
[23:21:45] - Received Items -
[23:21:45] [ITEM] ItemUltraBall x 25 
[23:21:45] [ITEM] ItemMaxPotion x 20 
[23:21:45] [ITEM] ItemRevive x 15 
[23:21:45] [ITEM] ItemRazzBerry x 15 
[23:21:45] [ITEM] ItemIncenseOrdinary x 1 
[23:21:45] [ITEM] ItemLuckyEgg x 1 
[23:21:45] [ITEM] ItemIncubatorBasic x 1 
[23:21:45] [ITEM] ItemTroyDisk x 1 
[23:21:50] Roucool +1000XP
[23:22:45] Rattata +1000XP
[23:22:50] Roucool +1000XP
[23:23:00] Rattata +1000XP
[23:23:04] Roucool +1000XP
[23:23:08] Rattata +1000XP
[23:23:12] Roucool +1000XP
[23:23:53] Rattata +1000XP
[23:23:56] Roucool +1000XP
[23:24:14] Rattata +1000XP
[23:24:18] Aspicot +1000XP
[23:25:14] Chenipan +1000XP
[23:25:17] Aspicot +1000XP
[23:25:21] Chenipan +1000XP
[23:25:26] Aspicot +1000XP
[23:25:30] Chenipan +1000XP
[23:25:34] Aspicot +1000XP
[23:26:12] Chenipan +1000XP
[23:26:18] Incubation en cours, reste 4,85km
[23:26:18] Roucoups    	-  737 /  40,30%   [Meilleur   740 /  41,85%] 44 Bonbons
[23:26:19] Incubation d'un oeuf, reste 5,00km
[23:26:22] Roucoups    	-  726 /  33,52%   [Meilleur   740 /  41,85%] 45 Bonbons
[23:26:27] Roucoups    	-  725 /  51,77%   [Meilleur   740 /  41,85%] 46 Bonbons
[23:26:32] Roucoups    	-  724 /  51,37%   [Meilleur   740 /  41,85%] 47 Bonbons
[23:26:37] Roucoups    	-  714 /  44,70%   [Meilleur   740 /  41,85%] 48 Bonbons
[23:26:42] Roucoups    	-  712 /  43,41%   [Meilleur   740 /  41,85%] 49 Bonbons
... (rest of the 69 evo transfered)
```

![scr](https://cloud.githubusercontent.com/assets/20887203/17536499/a46e476a-5e95-11e6-853f-19eacf358ff3.png)

**Comment by schwartzadev** [comment]
It is known that the current logging method is pretty bad. Not sure about the console though. Flagged as bug.

**Comment by fernaandogv** [comment]
help me solve this problem
![sin titulo](https://cloud.githubusercontent.com/assets/20937389/17537478/862b961e-5e62-11e6-9f64-dc8bb7ff42cc.png)

**Comment by cawk** [comment]
Can you check this there was an error with the logging system which was fixed earlier please check again

**Comment by Drunken88** [comment]
Still not good... the bot did 22 evolutions here and the console only displays 17
Same thing in the logs.

![scr](https://cloud.githubusercontent.com/assets/20887203/17607490/5a462af8-6026-11e6-8b70-d76564973f74.png)
